version: '2'
services:
  node:
    hostname: &hostname node-example.docker.amazee.io
    container_name: *hostname
    image: amazeeio/centos7-node-builder:8
    volumes:
      - .:/app:delegated
    command: bash -c "yarn install && npm run dev"
    network_mode: bridge
    expose:
      - "3000"
    environment:
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_URL=node-example.docker.amazee.io
      - AMAZEEIO_HTTP_PORT=3000
      ## set AMAZEEIO_GIT_BRANCH to the branch name that you would like to inject environment variables for
      #- AMAZEEIO_GIT_BRANCH=master